import hashlib
from pathlib import Path

import pytest
import vcr as vcrpy

from extract.downloader import download_file
from extract.hasher import Sha256Hasher
from extract.parser import generate_parquet_urls

CASSETTE_DIR = Path("tests/e2e/cassettes")
TEST_URL = generate_parquet_urls(datasets=["yellow"], years=[2015], months=[1])[0]
SAMPLE_BYTES = 5 * 1024 * 1024  # 5 MB

vcr = vcrpy.VCR(
    cassette_library_dir=str(CASSETTE_DIR),
    record_mode="none",  # never hit the network — cassettes must exist
)


def test_download_file_success_e2e(tmp_path):
    """
    E2E Test: Verifies that download_file writes the file correctly and
    returns the right path and SHA-256 hash.
    Replays from cassette generated by tests/e2e/create_cassettes.py.
    """
    download_dir = tmp_path / "e2e_downloads"

    with vcr.use_cassette("downloader_success.yaml") as cassette:
        result = download_file(TEST_URL, download_dir, Sha256Hasher())

        assert result is not None
        assert result.file_path.exists()
        assert result.file_path.name == TEST_URL.split("/")[-1]
        assert result.file_path.stat().st_size <= SAMPLE_BYTES
        assert result.hash_type == "sha256"

        content = result.file_path.read_bytes()
        assert result.hash_value == hashlib.sha256(content).hexdigest()

        # 1 HEAD (size check) + 1 GET (download).
        assert len(cassette.requests) >= 2


def test_download_file_idempotency_e2e(tmp_path):
    """
    E2E Test: Verifies idempotency -- the second call skips the GET because
    the file already exists with the correct size.
    Replays from cassette generated by tests/e2e/create_cassettes.py.
    """
    download_dir = tmp_path / "idempotency_downloads"

    with vcr.use_cassette("downloader_idempotency.yaml") as cassette:
        # First call: HEAD + GET.
        result1 = download_file(TEST_URL, download_dir, Sha256Hasher())

        first_run_request_count = cassette.play_count

        # Second call: HEAD only (file exists with matching size).
        result2 = download_file(TEST_URL, download_dir, Sha256Hasher())

        assert result1 is not None
        assert result2 is not None
        assert result1.file_path == result2.file_path
        assert result1.hash_value == result2.hash_value
        assert result1.hash_type == result2.hash_type

        # Only one additional HEAD, no GET.
        assert cassette.play_count == first_run_request_count + 1


def test_download_file_checksum_failure_e2e(tmp_path, caplog):
    """
    E2E Test: Verifies that an incorrect expected_hash logs a warning but does not raise.
    The expected_hash is informational — used for dedup in upload, not validation.
    Replays from cassette generated by tests/e2e/create_cassettes.py.
    """
    import logging

    download_dir = tmp_path / "checksum_fail_downloads"
    wrong_hash = "0000000000000000000000000000000000000000000000000000000000000000"

    with vcr.use_cassette("downloader_checksum_fail.yaml") as cassette:
        with caplog.at_level(logging.WARNING):
            result = download_file(TEST_URL, download_dir, Sha256Hasher(), expected_hash=wrong_hash)

        assert result is not None
        assert result.file_path.exists()
        assert result.file_path.name == TEST_URL.split("/")[-1]
        assert result.hash_type == "sha256"
        assert any(
            "Checksum mismatch" in record.message
            for record in caplog.records
        ), f"Expected checksum warning, got: {[r.message for r in caplog.records]}"


def test_download_file_not_found_e2e(tmp_path, caplog):
    """
    E2E Test: Verifies that a 404 Not Found response from the server
    results in None and logs a warning.
    """
    download_dir = tmp_path / "not_found_downloads"

    with vcr.use_cassette("downloader_not_found.yaml"):
        result = download_file(TEST_URL, download_dir, Sha256Hasher())
        assert result is None
        assert any("File not found" in record.message for record in caplog.records)


def test_download_file_forbidden_e2e(tmp_path, caplog):
    """
    E2E Test: Verifies that a 403 Forbidden response from the server
    results in None and logs a warning.
    """
    download_dir = tmp_path / "forbidden_downloads"

    with vcr.use_cassette("downloader_forbidden.yaml"):
        result = download_file(TEST_URL, download_dir, Sha256Hasher())
        assert result is None
        assert any("Access forbidden" in record.message for record in caplog.records)
