"""
Fuzz test for extract.parser.generate_parquet_urls

Based on the actual implementation of parser.py:
- VALID_DATASETS = {"yellow", "green", "fhv", "hvfhv"}
- _check_dataset: TypeError if not str, ValueError if not in set
- _check_year: TypeError if not int or if bool
- _check_month: TypeError if not int or if bool, ValueError if outside 1-12
- _validate_*: TypeError if not iterable (e.g. years=None)
- datasets=None uses all 4 valid ones
"""

import sys

import atheris

with atheris.instrument_imports():
    from extract.parser import BASE_S3_URL, VALID_DATASETS, generate_parquet_urls

VALID_DATASETS_LIST = sorted(VALID_DATASETS)

EXPECTED_EXCEPTIONS = (TypeError, ValueError)


# ── Helpers ───────────────────────────────────────────────────────────────────


def _consume_valid_datasets(fdp, min_items=1):
    """Generates a list of valid datasets using the fuzzer."""
    num = fdp.ConsumeIntInRange(min_items, 4)
    return [fdp.PickValueInList(VALID_DATASETS_LIST) for _ in range(num)]


def _consume_years(fdp, min_items=1):
    """Generates a list of years using the fuzzer."""
    num = fdp.ConsumeIntInRange(min_items, 5)
    return [fdp.ConsumeIntInRange(2009, 2025) for _ in range(num)]


def _consume_months(fdp, min_items=1):
    """Generates a list of valid months using the fuzzer."""
    num = fdp.ConsumeIntInRange(min_items, 12)
    return [fdp.ConsumeIntInRange(1, 12) for _ in range(num)]


def _assert_valid_result(result, datasets, years, months):
    """Checks invariants when the function returns successfully."""

    assert isinstance(result, list), f"Return should be a list, received {type(result)}"

    for url in result:
        assert isinstance(url, str), f"Each URL should be a string: {url!r}"
        assert url.startswith(BASE_S3_URL), f"URL with wrong prefix: {url}"
        assert url.endswith(".parquet"), f"URL should end with .parquet: {url}"

    u_datasets = len(set(datasets))
    u_years = len(set(years))
    u_months = len(set(months))
    expected = u_datasets * u_years * u_months

    assert len(result) == expected, (
        f"Wrong count: expected {expected} ({u_datasets}d x {u_years}y x {u_months}m), "
        f"received {len(result)}"
    )

    # Chronological order by dataset
    for dataset in set(datasets):
        dataset_urls = [u for u in result if f"/{dataset}_tripdata_" in u]
        dates = []
        for url in dataset_urls:
            date_part = url.split("_tripdata_")[-1].replace(".parquet", "")
            y, m = date_part.split("-")
            dates.append((int(y), int(m)))
        assert dates == sorted(dates), (
            f"Dataset '{dataset}' out of chronological order: {dates}"
        )


# ── Strategy 1: valid inputs + invariants ───────────────────────────────────


def fuzz_valid_seeds(data):
    """
    All parameters generated by the fuzzer within valid values.
    Checks count, format, and order invariants.
    """
    fdp = atheris.FuzzedDataProvider(data)

    try:
        datasets = _consume_valid_datasets(fdp)
        years = _consume_years(fdp)
        months = _consume_months(fdp)

        result = generate_parquet_urls(datasets=datasets, years=years, months=months)

        _assert_valid_result(result, datasets, years, months)

    except EXPECTED_EXCEPTIONS:
        pass
    except Exception as e:
        raise e


# ── Strategy 2: wrong types in fields ───────────────────────────────────────


def fuzz_wrong_types(data):
    """
    Tests type guards with other parameters varying freely.
    No fixed value — the fuzzer controls everything.
    """
    fdp = atheris.FuzzedDataProvider(data)

    try:
        case = fdp.ConsumeIntInRange(0, 7)

        if case == 0:
            # bool rejected as year — datasets and months vary
            datasets = _consume_valid_datasets(fdp)
            months = _consume_months(fdp)
            generate_parquet_urls(datasets, [True], months)

        elif case == 1:
            # bool rejected as month — datasets and years vary
            datasets = _consume_valid_datasets(fdp)
            years = _consume_years(fdp)
            generate_parquet_urls(datasets, years, [False])

        elif case == 2:
            # string instead of year — datasets and months vary
            datasets = _consume_valid_datasets(fdp)
            bad_year = fdp.ConsumeUnicode(10)
            months = _consume_months(fdp)
            generate_parquet_urls(datasets, [bad_year], months)

        elif case == 3:
            # string instead of month — datasets and years vary
            datasets = _consume_valid_datasets(fdp)
            years = _consume_years(fdp)
            bad_month = fdp.ConsumeUnicode(10)
            generate_parquet_urls(datasets, years, [bad_month])

        elif case == 4:
            # int instead of dataset — years and months vary
            bad_dataset = fdp.ConsumeInt(4)
            years = _consume_years(fdp)
            months = _consume_months(fdp)
            generate_parquet_urls([bad_dataset], years, months)

        elif case == 5:
            # years=None — datasets and months vary
            datasets = _consume_valid_datasets(fdp)
            months = _consume_months(fdp)
            generate_parquet_urls(datasets, None, months)

        elif case == 6:
            # months=None — datasets and years vary
            datasets = _consume_valid_datasets(fdp)
            years = _consume_years(fdp)
            generate_parquet_urls(datasets, years, None)

        elif case == 7:
            # float instead of month — datasets and years vary
            datasets = _consume_valid_datasets(fdp)
            years = _consume_years(fdp)
            bad_month = fdp.ConsumeFloat()
            generate_parquet_urls(datasets, years, [bad_month])

    except EXPECTED_EXCEPTIONS:
        pass
    except Exception as e:
        raise e


# ── Strategy 3: out-of-range values ───────────────────────────────────────────


def fuzz_out_of_range(data):
    """
    Tests invalid ranges with all parameters varying.
    """
    fdp = atheris.FuzzedDataProvider(data)

    try:
        case = fdp.ConsumeIntInRange(0, 3)

        if case == 0:
            # Month > 12 — datasets and years vary
            datasets = _consume_valid_datasets(fdp)
            years = _consume_years(fdp)
            bad_month = fdp.ConsumeIntInRange(13, 100000)
            generate_parquet_urls(datasets, years, [bad_month])

        elif case == 1:
            # Month < 1 — datasets and years vary
            datasets = _consume_valid_datasets(fdp)
            years = _consume_years(fdp)
            bad_month = fdp.ConsumeIntInRange(-100000, 0)
            generate_parquet_urls(datasets, years, [bad_month])

        elif case == 2:
            # Invalid dataset — years and months vary
            bad_dataset = fdp.ConsumeUnicode(30)
            years = _consume_years(fdp)
            months = _consume_months(fdp)
            generate_parquet_urls([bad_dataset], years, months)

        elif case == 3:
            # Mix of valid + invalid — years and months vary
            valid = fdp.PickValueInList(VALID_DATASETS_LIST)
            invalid = fdp.ConsumeUnicode(20)
            years = _consume_years(fdp)
            months = _consume_months(fdp)
            generate_parquet_urls([valid, invalid], years, months)

    except EXPECTED_EXCEPTIONS:
        pass
    except Exception as e:
        raise e


# ── Strategy 4: datasets=None ─────────────────────────────────────────────────


def fuzz_none_datasets(data):
    """
    datasets=None should return exactly 4 * years * months URLs
    with all 4 datasets present.
    """
    fdp = atheris.FuzzedDataProvider(data)

    try:
        years = list(
            {
                fdp.ConsumeIntInRange(2009, 2025)
                for _ in range(fdp.ConsumeIntInRange(1, 5))
            }
        )
        months = list(
            {fdp.ConsumeIntInRange(1, 12) for _ in range(fdp.ConsumeIntInRange(1, 12))}
        )

        result = generate_parquet_urls(datasets=None, years=years, months=months)

        assert isinstance(result, list)

        expected = 4 * len(years) * len(months)
        assert len(result) == expected, (
            f"datasets=None: expected {expected} URLs, received {len(result)}"
        )

        found_datasets = {url.split("/")[-1].split("_")[0] for url in result}
        assert found_datasets == VALID_DATASETS, (
            f"datasets=None should contain the 4 datasets, received: {found_datasets}"
        )

    except EXPECTED_EXCEPTIONS:
        pass
    except Exception as e:
        raise e


# ── Strategy 5: empty lists ───────────────────────────────────────────────────


def fuzz_empty_inputs(data):
    """
    Empty list in any parameter should return [] without crashing.
    Other parameters vary freely to test combinations.
    """
    fdp = atheris.FuzzedDataProvider(data)

    try:
        case = fdp.ConsumeIntInRange(0, 2)

        if case == 0:
            # empty datasets — years and months vary
            years = _consume_years(fdp)
            months = _consume_months(fdp)
            result = generate_parquet_urls([], years, months)
            assert result == [], f"datasets=[] should return [], received {result}"

        elif case == 1:
            # empty years — datasets and months vary
            datasets = _consume_valid_datasets(fdp)
            months = _consume_months(fdp)
            result = generate_parquet_urls(datasets, [], months)
            assert result == [], f"years=[] should return [], received {result}"

        elif case == 2:
            # empty months — datasets and years vary
            datasets = _consume_valid_datasets(fdp)
            years = _consume_years(fdp)
            result = generate_parquet_urls(datasets, years, [])
            assert result == [], f"months=[] should return [], received {result}"

    except EXPECTED_EXCEPTIONS:
        pass
    except Exception as e:
        raise e


# ── Entry point ───────────────────────────────────────────────────────────────


def test_one_input(data):
    """
    Runs all strategies in each execution.
    libFuzzer mutates bytes seeking to increase coverage in any of them.
    """
    fuzz_valid_seeds(data)
    fuzz_wrong_types(data)
    fuzz_out_of_range(data)
    fuzz_none_datasets(data)
    fuzz_empty_inputs(data)


if __name__ == "__main__":
    atheris.Setup(sys.argv, test_one_input)
    atheris.Fuzz()
